version: '3.4'



services:

  calculationscript:

    image: jmeter_generator

    build:

      context: .

      dockerfile: ./Dockerfile

    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 script.py "]

    ports:

      - 5678:5678

