version: '3.4'



services:

  jmeter_generator:

    image: jmeter_generator

    build:

      context: .

      dockerfile: ./Dockerfile

    volumes:

      - ./data:/home/ivangananjaya/Documents/Docker_Volume

    command: tail -F anything